default: &default
  adapter: mysql2
  encoding: utf8
  host: db #docker-compose.yml の service 名
  username: root
  password: password # docker-compose.ymlのMYSQL_ROOT_PASSWORD
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test